on:
  workflow_dispatch:

name: Build and upload docs

jobs:
  this:
    name: Build and publish release
    runs-on: ubuntu-latest
    env:
      FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.PLATFORM_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PLATFORM_AWS_SECRET_ACCESS_KEY }}
      SESSION_NAME: gh-action/${{ github.workflow }}          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docs
        run: scripts/build-docs.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PLATFORM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PLATFORM_AWS_SECRET_ACCESS_KEY }}        
          role-to-assume: arn:aws:iam::733578946173:role/platform-deploy
          aws-region: eu-west-1
          role-skip-session-tagging: true
          role-duration-seconds: 900          
      - name: Upload docs to aslive
        run: |
          scripts/upload-docs.sh aslive

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PLATFORM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PLATFORM_AWS_SECRET_ACCESS_KEY }}     
          role-to-assume: arn:aws:iam::371640587010:role/platform-deploy
          aws-region: eu-west-1
          role-skip-session-tagging: true
          role-duration-seconds: 900          
      - name: Upload docs to live
        run: |
          scripts/upload-docs.sh live
